### ISSUE TITLE
Comment color

### ISSUE THREAD

**Issue by TimBu63** [eemed/sitruuna.vim#1]
I apologize if this is a dumb question. I'm using VIM on CentOS 7 (cterm, not gui).

The line numbers in the left column are the comment color, but comments in the main pane are a light blue color. Any idea why and how to fix?

**Comment by eemed** [comment]
Ive been experimenting with the colorscheme to fit my tastes better. I forgot to update the xterm colors along the way.

**Comment by eemed** [comment]
Updated xterm colors.
