### ISSUE TITLE
How can I install this theme manually?

### ISSUE THREAD

**Issue by erlonpr** [eemed/sitruuna.vim#2]
First of all, I would like to thank you for the great work with this theme for Vim.
I would like to know if it is possible to install the theme _manually_ and, if possible, how can I do this?

I structured the theme files like this inside the .**vim** directory:

```
.vim
|-- colors
|       |-- sitruuna.vim    
|
|-- autoload
        |-- lightline
                |-- colorscheme
                        |-- sitruuna.vim                 
```

And put it like this in the **.vimrc** file:
```
syntax enable
colorscheme sitruuna
```

**Comment by eemed** [comment]
```
.vim
|-- colors
        |-- sitruuna.vim    
```
this works for me. I would suggest you atleast use the built in package manager.
See :h packadd

for a short example:
```
.vim
└── pack
    └── foo
        └── opt
            └── sitruuna.vim
                ├── autoload
                │   └── lightline
                │       └── colorscheme
                │           └── sitruuna.vim
                ├── colors
                │   └── sitruuna.vim
                ├── LICENSE
                └── README.md

```
Make the directory `mkdir -p .vim/pack/<anything>/opt/` and clone the plugin using `git clone https://github.com/eemed/sitruuna.vim` Minimal .vimrc would be
```
set nocompatible
syntax enable                                                                                                           
packadd! sitruuna.vim 
```

Hope this helps.

**Comment by erlonpr** [comment]
@eemed thanks for the help.
